In [9]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline
from datetime import datetime
from numpy.linalg import LinAlgError
from dateutil.parser import parse
import statsmodels.formula.api as smf
import statsmodels.api as sm
from matplotlib.pylab import rcParams
rcParams['figure.figsize'] = 15, 6
import math
import nltk
import re

In [10]:
df = pd.read_csv('C:/Users/Maha/Desktop/spam/SPAM text message 20170820 - Data.csv')
#df = df.reset_index(drop=True)
df.head(5)

bCategory                                            Message
0       ham  Go until jurong point, crazy.. Available only ...
1       ham                      Ok lar... Joking wif u oni...
2      spam  Free entry in 2 a wkly comp to win FA Cup fina...
3       ham  U dun say so early hor... U c already then say...
4       ham  Nah I don't think he goes to usf, he lives aro...

In [11]:
print(len(df))

5572


In [12]:
df[df['bCategory'] =='ham'].count()

bCategory    4825
Message      4825
dtype: int64

# Length

In [13]:
df['Length'] = ""
for index,row in df.iterrows():
    tokens =  nltk.regexp_tokenize(row['Message'], "\w+")
    words = [w.lower for w in tokens]
    row['Length'] = len(words)

In [14]:
df.head(5)

bCategory                                            Message Length
0       ham  Go until jurong point, crazy.. Available only ...     20
1       ham                      Ok lar... Joking wif u oni...      6
2      spam  Free entry in 2 a wkly comp to win FA Cup fina...     33
3       ham  U dun say so early hor... U c already then say...     11
4       ham  Nah I don't think he goes to usf, he lives aro...     14

# Presence of Mathematic Symbol

In [15]:
df['Mathematic Symbol'] = ""
for index,row in df.iterrows():
    regex = r"(?=.[<\^\+\/>])"
    if re.search(regex, row['Message']):
        row['Mathematic Symbol'] = 1
    else:
        row['Mathematic Symbol'] = 0

# Presence of URLs

In [16]:
df['URL'] = ''
for index,row in df.iterrows():
    regex = r"[-a-zA-Z0-9@:%._\+~#=]{2,256}\.[a-z]{2,6}\b([-a-zA-Z0-9@:%_\+.~#?&//=]*)"
    if re.search(regex, row['Message']):
        row['URL'] = 1
    else:
        row['URL'] = 0

# Presence of Dots

In [17]:
df['Dots'] = ''
for index,row in df.iterrows():
    regex =  r"(?=.[.])"
    if re.search(regex, row['Message']):
        row['Dots'] = 1
    else:
        row['Dots'] = 0

In [18]:
df.head(5)

bCategory                                            Message Length  \
0       ham  Go until jurong point, crazy.. Available only ...     20   
1       ham                      Ok lar... Joking wif u oni...      6   
2      spam  Free entry in 2 a wkly comp to win FA Cup fina...     33   
3       ham  U dun say so early hor... U c already then say...     11   
4       ham  Nah I don't think he goes to usf, he lives aro...     14   

  Mathematic Symbol URL Dots  
0                 0   0    1  
1                 0   0    1  
2                 0   0    1  
3                 0   0    1  
4                 0   0    0

In [19]:
df['Special Symbols'] = ''
for index,row in df.iterrows():
    regex =  r"(?=.[$£€!*#&])"
    if re.search(regex, row['Message']):
        row['Special Symbols'] = 1
    else:
        row['Special Symbols'] = 0

In [20]:
df.head(5)

bCategory                                            Message Length  \
0       ham  Go until jurong point, crazy.. Available only ...     20   
1       ham                      Ok lar... Joking wif u oni...      6   
2      spam  Free entry in 2 a wkly comp to win FA Cup fina...     33   
3       ham  U dun say so early hor... U c already then say...     11   
4       ham  Nah I don't think he goes to usf, he lives aro...     14   

  Mathematic Symbol URL Dots Special Symbols  
0                 0   0    1               0  
1                 0   0    1               0  
2                 0   0    1               1  
3                 0   0    1               0  
4                 0   0    0               0

In [21]:
df['Phone number'] = ''
for index,row in df.iterrows():
    regex =  r"(\d{3}[-\.\s]??\d{3}[-\.\s]??\d{4}|\(\d{3}\)\s*\d{3}[-\.\s]??\d{4}|\d{3}[-\.\s]??\d{4})"
    if re.search(regex, row['Message']):
        row['Phone number'] = 1
    else:
        row['Phone number'] = 0

df['Presence of emotions'] = ''
for index,row in df.iterrows():
    regex =  r"[:) :( -_- :p  :v  :* :o B-) :'( ]"
    if re.search(regex, row['Message']):
        row['Phone number'] = 1
    else:
        row['Phone number'] = 0

In [22]:
df.head(20)

bCategory                                            Message Length  \
0        ham  Go until jurong point, crazy.. Available only ...     20   
1        ham                      Ok lar... Joking wif u oni...      6   
2       spam  Free entry in 2 a wkly comp to win FA Cup fina...     33   
3        ham  U dun say so early hor... U c already then say...     11   
4        ham  Nah I don't think he goes to usf, he lives aro...     14   
5       spam  FreeMsg Hey there darling it's been 3 week's n...     36   
6        ham  Even my brother is not like to speak with me. ...     16   
7        ham  As per your request 'Melle Melle (Oru Minnamin...     26   
8       spam  WINNER!! As a valued network customer you have...     26   
9       spam  Had your mobile 11 months or more? U R entitle...     29   
10       ham  I'm gonna be home soon and i don't want to tal...     24   
11      spam  SIX chances to win CASH! From 100 to 20,000 po...     28   
12      spam  URGENT! You have won a 1 week FREE membership ...     30   
13       ham  I've been searching for the right words to tha...     38   
14       ham                I HAVE A DATE ON SUNDAY WITH WILL!!      8   
15      spam  XXXMobileMovieClub: To use your credit, click ...     23   
16       ham                         Oh k...i'm watching here:)      6   
17       ham  Eh u remember how 2 spell his name... Yes i di...     19   
18       ham  Fine if that’s the way u feel. That’s the way ...     15   
19      spam  England v Macedonia - dont miss the goals/team...     27   

   Mathematic Symbol URL Dots Special Symbols Phone number  
0                  0   0    1               0            0  
1                  0   0    1               0            0  
2                  0   0    1               1            1  
3                  0   0    1               0            0  
4                  0   0    0               0            0  
5                  0   0    1               1            0  
6                  0   0    1               0            0  
7                  0   0    1               1            0  
8                  0   0    1               1            1  
9                  0   0    0               1            1  
10                 0   0    1               0            0  
11                 1   0    1               1            0  
12                 0   1    1               1            0  
13                 0   0    1               0            0  
14                 0   0    0               1            0  
15                 1   1    1               0            0  
16                 0   0    1               0            0  
17                 0   0    1               0            0  
18                 0   0    1               0            0  
19                 1   0    1               0            0

In [23]:
del df['Message']

In [24]:
X = df.drop('bCategory', axis=1)  
y = df['bCategory'] 

In [25]:
from sklearn.model_selection import train_test_split  
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.30) 

# Linear SVM

In [26]:
from sklearn.svm import SVC  
svclassifier = SVC(kernel='linear')  
svclassifier.fit(X_train, y_train) 

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='linear',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [27]:
y_pred = svclassifier.predict(X_test) 

In [28]:
from sklearn.metrics import classification_report, confusion_matrix  
print(confusion_matrix(y_test,y_pred))  
print(classification_report(y_test,y_pred)) 

[[1429   15]
 [  53  175]]
             precision    recall  f1-score   support

        ham       0.96      0.99      0.98      1444
       spam       0.92      0.77      0.84       228

avg / total       0.96      0.96      0.96      1672



# Decision trees

In [29]:
from sklearn.tree import DecisionTreeClassifier
clf_gini = DecisionTreeClassifier(criterion = "gini", random_state = 100,
                               max_depth=3, min_samples_leaf=5)
clf_gini.fit(X_train, y_train)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=3,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=5, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=100,
            splitter='best')

In [30]:
y_pred = clf_gini.predict(X_test)

In [31]:
print(confusion_matrix(y_test,y_pred))  
print(classification_report(y_test,y_pred)) 

[[1435    9]
 [  57  171]]
             precision    recall  f1-score   support

        ham       0.96      0.99      0.98      1444
       spam       0.95      0.75      0.84       228

avg / total       0.96      0.96      0.96      1672



# Naive Bayes

In [25]:
from sklearn.naive_bayes import GaussianNB

In [26]:
gnb = GaussianNB()

In [27]:
gnb.fit(X_train, y_train)

GaussianNB(priors=None)

In [28]:
y_pred = gnb.predict(X_test)

In [29]:
print(confusion_matrix(y_test,y_pred))  
print(classification_report(y_test,y_pred)) 

[[1432   28]
 [  42  170]]
             precision    recall  f1-score   support

        ham       0.97      0.98      0.98      1460
       spam       0.86      0.80      0.83       212

avg / total       0.96      0.96      0.96      1672



# Random Forest

In [30]:
from sklearn.ensemble import RandomForestClassifier

In [31]:
clf = RandomForestClassifier(max_depth=2, random_state=0)

In [32]:
clf.fit(X_train, y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=2, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=1,
            oob_score=False, random_state=0, verbose=0, warm_start=False)

In [33]:
print(clf.feature_importances_)

[ 0.10716812  0.36032924  0.01875718  0.0011249   0.10560713  0.40701343]


In [34]:
y_pred = clf.predict(X_test)

In [35]:
print(confusion_matrix(y_test,y_pred))  
print(classification_report(y_test,y_pred)) 

[[1453    7]
 [  68  144]]
             precision    recall  f1-score   support

        ham       0.96      1.00      0.97      1460
       spam       0.95      0.68      0.79       212

avg / total       0.96      0.96      0.95      1672



# Logistic regression

In [36]:
from sklearn.linear_model import LogisticRegression
# all parameters not specified are set to their defaults
logisticRegr = LogisticRegression()
logisticRegr.fit(X_train, y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [37]:
y_pred = logisticRegr.predict(X_test)

In [38]:
print(confusion_matrix(y_test,y_pred))  
print(classification_report(y_test,y_pred))

[[1448   12]
 [  52  160]]
             precision    recall  f1-score   support

        ham       0.97      0.99      0.98      1460
       spam       0.93      0.75      0.83       212

avg / total       0.96      0.96      0.96      1672



# KNN

In [42]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=5)

In [43]:
knn.fit(X_train, y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=5, p=2,
           weights='uniform')

In [48]:
y_pred = knn.predict(X_test)

In [49]:
print(confusion_matrix(y_test,y_pred))  
print(classification_report(y_test,y_pred))

[[1440   20]
 [  76  136]]
             precision    recall  f1-score   support

        ham       0.95      0.99      0.97      1460
       spam       0.87      0.64      0.74       212

avg / total       0.94      0.94      0.94      1672

